// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.3
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// CONTROL
// 0x0000 : Control signals
//          bit 0  - ap_start (Read/Write/COH)
//          bit 1  - ap_done (Read/COR)
//          bit 2  - ap_idle (Read)
//          bit 3  - ap_ready (Read)
//          bit 7  - auto_restart (Read/Write)
//          others - reserved
// 0x0004 : Global Interrupt Enable Register
//          bit 0  - Global Interrupt Enable (Read/Write)
//          others - reserved
// 0x0008 : IP Interrupt Enable Register (Read/Write)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x000c : IP Interrupt Status Register (Read/TOW)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x0010 : Data signal of stepsMC
//          bit 31~0 - stepsMC[31:0] (Read/Write)
// 0x0014 : reserved
// 0x4000 : Data signal of peekStep
//          bit 31~0 - peekStep[31:0] (Read)
// 0x4004 : Control signal of peekStep
//          bit 0  - peekStep_ap_vld (Read/COR)
//          others - reserved
// 0x1000 ~
// 0x1fff : Memory 'b0_vector' (1024 * 32b)
//          Word n : bit [31:0] - b0_vector[n]
// 0x2000 ~
// 0x2fff : Memory 'b1_vector' (1024 * 32b)
//          Word n : bit [31:0] - b1_vector[n]
// 0x3000 ~
// 0x3fff : Memory 'b2_vector' (1024 * 32b)
//          Word n : bit [31:0] - b2_vector[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCHOLESKYREGIO_CONTROL_ADDR_AP_CTRL        0x0000
#define XCHOLESKYREGIO_CONTROL_ADDR_GIE            0x0004
#define XCHOLESKYREGIO_CONTROL_ADDR_IER            0x0008
#define XCHOLESKYREGIO_CONTROL_ADDR_ISR            0x000c
#define XCHOLESKYREGIO_CONTROL_ADDR_STEPSMC_DATA   0x0010
#define XCHOLESKYREGIO_CONTROL_BITS_STEPSMC_DATA   32
#define XCHOLESKYREGIO_CONTROL_ADDR_PEEKSTEP_DATA  0x4000
#define XCHOLESKYREGIO_CONTROL_BITS_PEEKSTEP_DATA  32
#define XCHOLESKYREGIO_CONTROL_ADDR_PEEKSTEP_CTRL  0x4004
#define XCHOLESKYREGIO_CONTROL_ADDR_B0_VECTOR_BASE 0x1000
#define XCHOLESKYREGIO_CONTROL_ADDR_B0_VECTOR_HIGH 0x1fff
#define XCHOLESKYREGIO_CONTROL_WIDTH_B0_VECTOR     32
#define XCHOLESKYREGIO_CONTROL_DEPTH_B0_VECTOR     1024
#define XCHOLESKYREGIO_CONTROL_ADDR_B1_VECTOR_BASE 0x2000
#define XCHOLESKYREGIO_CONTROL_ADDR_B1_VECTOR_HIGH 0x2fff
#define XCHOLESKYREGIO_CONTROL_WIDTH_B1_VECTOR     32
#define XCHOLESKYREGIO_CONTROL_DEPTH_B1_VECTOR     1024
#define XCHOLESKYREGIO_CONTROL_ADDR_B2_VECTOR_BASE 0x3000
#define XCHOLESKYREGIO_CONTROL_ADDR_B2_VECTOR_HIGH 0x3fff
#define XCHOLESKYREGIO_CONTROL_WIDTH_B2_VECTOR     32
#define XCHOLESKYREGIO_CONTROL_DEPTH_B2_VECTOR     1024

