// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.3
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// CONTROL
// 0x0000 : Control signals
//          bit 0  - ap_start (Read/Write/COH)
//          bit 1  - ap_done (Read/COR)
//          bit 2  - ap_idle (Read)
//          bit 3  - ap_ready (Read)
//          bit 7  - auto_restart (Read/Write)
//          others - reserved
// 0x0004 : Global Interrupt Enable Register
//          bit 0  - Global Interrupt Enable (Read/Write)
//          others - reserved
// 0x0008 : IP Interrupt Enable Register (Read/Write)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x000c : IP Interrupt Status Register (Read/TOW)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x0010 : Data signal of amount
//          bit 31~0 - amount[31:0] (Read/Write)
// 0x0014 : reserved
// 0x0018 : Data signal of peekAmountFwd
//          bit 31~0 - peekAmountFwd[31:0] (Read)
// 0x001c : Control signal of peekAmountFwd
//          bit 0  - peekAmountFwd_ap_vld (Read/COR)
//          others - reserved
// 0x0020 : Data signal of peekAmountRev
//          bit 31~0 - peekAmountRev[31:0] (Read)
// 0x0024 : Control signal of peekAmountRev
//          bit 0  - peekAmountRev_ap_vld (Read/COR)
//          others - reserved
// 0x1000 ~
// 0x1fff : Memory 'seeds' (624 * 32b)
//          Word n : bit [31:0] - seeds[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMTFLEXREGO_CONTROL_ADDR_AP_CTRL            0x0000
#define XMTFLEXREGO_CONTROL_ADDR_GIE                0x0004
#define XMTFLEXREGO_CONTROL_ADDR_IER                0x0008
#define XMTFLEXREGO_CONTROL_ADDR_ISR                0x000c
#define XMTFLEXREGO_CONTROL_ADDR_AMOUNT_DATA        0x0010
#define XMTFLEXREGO_CONTROL_BITS_AMOUNT_DATA        32
#define XMTFLEXREGO_CONTROL_ADDR_PEEKAMOUNTFWD_DATA 0x0018
#define XMTFLEXREGO_CONTROL_BITS_PEEKAMOUNTFWD_DATA 32
#define XMTFLEXREGO_CONTROL_ADDR_PEEKAMOUNTFWD_CTRL 0x001c
#define XMTFLEXREGO_CONTROL_ADDR_PEEKAMOUNTREV_DATA 0x0020
#define XMTFLEXREGO_CONTROL_BITS_PEEKAMOUNTREV_DATA 32
#define XMTFLEXREGO_CONTROL_ADDR_PEEKAMOUNTREV_CTRL 0x0024
#define XMTFLEXREGO_CONTROL_ADDR_SEEDS_BASE         0x1000
#define XMTFLEXREGO_CONTROL_ADDR_SEEDS_HIGH         0x1fff
#define XMTFLEXREGO_CONTROL_WIDTH_SEEDS             32
#define XMTFLEXREGO_CONTROL_DEPTH_SEEDS             624

